version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-extensions:/opt/sonarqube/extensions
    restart: unless-stopped

volumes:
  sonar-db-data:
  sonar-data:
  sonar-logs:
  sonar-extensions:

# sqp_e0ff3f6e891b08b778d252af96cc7e3d2154937e